# Generated by Django 4.1.7 on 2023-08-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lstat", models.FloatField()),
                ("rm", models.FloatField()),
                ("ptratio", models.FloatField()),
                ("prediction", models.FloatField()),
            ],
        ),
    ]
